language: c
#######################################################################################
os:
  - linux
  
sudo: enabled

addons:
  apt:
    packages:
      - curl

#######################################################################################


before_install:

  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential kernel-package libncurses5-dev bzip2 git make -y
  - git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/ ~/aarch64-linux-android-4.9/
  - sudo chmod -R a+x *

#######################################################################################


script:  
  
  - export export CROSS_COMPILE=~/aarch64-linux-android-4.9/bin/aarch64-linux-android-
  - export ARCH_MTK_PLATFORM=mt6753
  - export ARCH=arm64
  - export KBUILD_BUILD_USER="ALGPHELLO"
  - export KBUILD_BUILD_HOST="fujitsu"
  - KERNEL_DIR=$PWD/android_kernel_gionee_gnsz6753_66_nougat
  - ZIMAGE=$KERNEL_DIR/arch/arm64/boot/Image
  - mkdir -p out
  - make gnsz6753_66_n_defconfig
  - make -j16
 
deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN_TB"
  
  on:
    tags: false
    repo: ALGPHELLO/android_kernel_gionee_gnsz6753_66_nougat
    branch: master

branches:
  except:
    - /^(?i:untagged)-.*$/
